# Nome do projeto
spring.application.name=loja

# Conexão com o Banco de Dados
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto (Opcional nas versões novas do Spring Boot)
# O Spring 3+ já detecta o dialeto moderno do MySQL sozinho
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#variaveis de ambiente
jwt.secret=${JWT_SECRET}


#tart-mail
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rafaelrodigues87@gmail.com
spring.mail.password=exor lxdk bzqb qmfo    
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.open-in-view=false   